### ISSUE TITLE
Don't fail if DefaultAppPool doesn't exist

### ISSUE THREAD

**Issue by Zuig4turi** [Microsoft/IIS.ServiceMonitor#39]
So i started fiddling around with Azure container instances and it works like a charm with linux container images. But when i try to deploy a windows container instance then the ACI continuously restarts and the state is set to waiting.
In logs it says

Service 'w3svc' has been stopped 

APPCMD failed with error code 183

Failed to update IIS configuration

The image that i am using is a public image in my docker repo.
It has a custom website running inside of it on IIS. Base image was a microsoft/nanoserver .
Any help would be much appreciated.

**Comment by shirhatti** [comment]
@Zuig4turi I don't believe there's anything ACI specific. I successfully deployed the microsoft/iis:nanoserver to ACI earlier this week.
That being said, there was an issue in the ServiceMonitor.exe included in the IIS image (prior to July 2017) that failed this exact APPCMD failure due to ServiceMonitor trying to create duplicate environment variables.

Could you retry by rebuilding your image on a newer iis base image?

**Comment by Zuig4turi** [comment]
Hello Shirhatti,
When i deploy microsoft/iis:nanoserver as a ACI it works perfectly fine.
If i customise the image in anyway it fails.
Lets say

docker run -d --name test microsoft/iis:nanoserver
docker stop test
docker commit test test_v1
docker login
docker tag test_v1 <reponame>:test_v1
docker push <reponame>:test_v1

Now when i use <reponame>:test_v1 in ACI it fails, and gives me error

Service 'w3svc' has been stopped

APPCMD failed with error code 183

Failed to update IIS configuration

**Comment by shirhatti** [comment]
@mcy94w Thoughts on this? This sounds exactly like https://github.com/Microsoft/iis-docker/issues/42 which I believe we'd already fixed a while ago

**Comment by shirhatti** [comment]
@Zuig4turi ServiceMonitor will promote environment variables from process environment it's own process environment block to the DefaultAppPool. We achieve this by naively copying all variables in our process environment block.

If you do end up replacing the default site, I'd recommend still using the Default App Pool otherwise you won't get environment variables to work. That being said, we can guard against it which we'll do in a future update

**Comment by michha** [comment]
@Zuig4turi 
Since #31 is merged, within the next release of the ServiceMonitor you should be able to remove the DefaultAppPool and get your custom pool monitored

**Comment by shirhatti** [comment]
@Zuig4turi feel free to re-open if you're still seeing this issue. As far as we're aware, this shouldn't be happening.
