### ISSUE TITLE
ServiceMonitor returns an error for Task Scheduler service

### ISSUE THREAD

**Issue by akunaatrium** [microsoft/IIS.ServiceMonitor#55]
To reproduce:

```
C:\Test>ServiceMonitor.exe Schedule

ERROR: Failed to start or query status of service 'Schedule' error [80070005]

ERROR: Failed to stop or query status of service 'Schedule' error [80070005]
```

And ServiceMonitor exits immediately.

Expected output would be something that indicates success and ServiceMonitor not quitting.

Operating system: Windows 10 Enterprise, version 1809, build 17763.437.

**Comment by bariscaglar** [comment]
That is an access denied error. We have not verified ServiceMonitor:
1. Outside container scenarios
2. Using services other than W3SVC.

That said, I think Task Scheduler service has a protected status. I can't control it manually through an elevated command prompt, either. That's why you're seeing an access denied error.
